### ISSUE TITLE
selecting 2 columns is not working

### ISSUE THREAD

**Issue by aleolopez** [tonytan4ever/Bootstrap-Form-Builder-V3V4#25]
Uncaught ReferenceError: _ is not defined

**Comment by tonytan4ever** [comment]
This should be fixed in here:
https://github.com/tonytan4ever/Bootstrap-Form-Builder-V3V4/commit/83f061bd69ad2232f30fc72f48f21a6c7c0a0eec on master (bootstrapV3)
And
https://github.com/tonytan4ever/Bootstrap-Form-Builder-V3V4/commit/a5e5f27f6f9c4e2b49110b1c709b5b7afd0b7bde on V4

Please verify and close this issue. 
Thanks for you QA effort !

**Comment by aleolopez** [comment]
you are the best, thx
